version: "3"

services:
  database:
    image: 'postgres'
    container_name: database
    restart: always
    env_file: .env
    ports:
        - 5432:5432
    volumes:
        - postgre_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file: .env
    ports:
      - 8080:8080
    depends_on:
      - database

volumes:
  postgre_data: { }
