# Generated by Django 5.1.2 on 2024-10-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("WORK", "Work"),
                            ("PERSONAL", "Personal"),
                            ("HEALTH", "Health"),
                        ],
                        max_length=50,
                        verbose_name="Category",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                ("description", models.TextField(verbose_name="Description")),
                ("date", models.DateTimeField(verbose_name="Date")),
                ("time", models.TimeField(verbose_name="Time")),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "events",
                "ordering": ["-date"],
            },
        ),
    ]
